(export (version D)
  (design
    (source /media/kentir1/Development/imakinGit/SBCExtended/KiCAD/SBCEx.sch)
    (date "Kam 17 Agu 2017 08:56:47  WIB")
    (tool "Eeschema 4.0.7-e1-6374~58~ubuntu14.04.1")
    (sheet (number 1) (name /) (tstamps /)
      (title_block
        (title)
        (company)
        (rev)
        (date)
        (source SBCEx.sch)
        (comment (number 1) (value ""))
        (comment (number 2) (value ""))
        (comment (number 3) (value ""))
        (comment (number 4) (value "")))))
  (components
    (comp (ref NANOL1)
      (value NanoLeft)
      (libsource (lib conn) (part CONN_01X15))
      (sheetpath (names /) (tstamps /))
      (tstamp 599594F1))
    (comp (ref NANOR1)
      (value NanoRight)
      (libsource (lib conn) (part CONN_01X15))
      (sheetpath (names /) (tstamps /))
      (tstamp 59959537))
    (comp (ref SBC_PIN1)
      (value CONN_02X20)
      (libsource (lib conn) (part CONN_02X20))
      (sheetpath (names /) (tstamps /))
      (tstamp 599595C4))
    (comp (ref DS1307)
      (value DS1307)
      (libsource (lib conn) (part CONN_01X05))
      (sheetpath (names /) (tstamps /))
      (tstamp 59959635))
    (comp (ref NANOP1)
      (value NanoProg)
      (libsource (lib conn) (part CONN_02X03))
      (sheetpath (names /) (tstamps /))
      (tstamp 599597B1)))
  (libparts
    (libpart (lib conn) (part CONN_01X05)
      (description "Connector, single row, 01x05, pin header")
      (footprints
        (fp Pin_Header_Straight_1X*)
        (fp Pin_Header_Angled_1X*)
        (fp Socket_Strip_Straight_1X*)
        (fp Socket_Strip_Angled_1X*))
      (fields
        (field (name Reference) J)
        (field (name Value) CONN_01X05))
      (pins
        (pin (num 1) (name P1) (type passive))
        (pin (num 2) (name P2) (type passive))
        (pin (num 3) (name P3) (type passive))
        (pin (num 4) (name P4) (type passive))
        (pin (num 5) (name P5) (type passive))))
    (libpart (lib conn) (part CONN_01X15)
      (description "Connector, single row, 01x15, pin header")
      (footprints
        (fp Pin_Header_Straight_1X*)
        (fp Pin_Header_Angled_1X*)
        (fp Socket_Strip_Straight_1X*)
        (fp Socket_Strip_Angled_1X*))
      (fields
        (field (name Reference) J)
        (field (name Value) CONN_01X15))
      (pins
        (pin (num 1) (name P1) (type passive))
        (pin (num 2) (name P2) (type passive))
        (pin (num 3) (name P3) (type passive))
        (pin (num 4) (name P4) (type passive))
        (pin (num 5) (name P5) (type passive))
        (pin (num 6) (name P6) (type passive))
        (pin (num 7) (name P7) (type passive))
        (pin (num 8) (name P8) (type passive))
        (pin (num 9) (name P9) (type passive))
        (pin (num 10) (name P10) (type passive))
        (pin (num 11) (name P11) (type passive))
        (pin (num 12) (name P12) (type passive))
        (pin (num 13) (name P13) (type passive))
        (pin (num 14) (name P14) (type passive))
        (pin (num 15) (name P15) (type passive))))
    (libpart (lib conn) (part CONN_02X03)
      (description "Connector, double row, 02x03, pin header")
      (footprints
        (fp Pin_Header_Straight_2X*)
        (fp Pin_Header_Angled_2X*)
        (fp Socket_Strip_Straight_2X*)
        (fp Socket_Strip_Angled_2X*)
        (fp IDC_Header_Straight_*))
      (fields
        (field (name Reference) J)
        (field (name Value) CONN_02X03))
      (pins
        (pin (num 1) (name P1) (type passive))
        (pin (num 2) (name P2) (type passive))
        (pin (num 3) (name P3) (type passive))
        (pin (num 4) (name P4) (type passive))
        (pin (num 5) (name P5) (type passive))
        (pin (num 6) (name P6) (type passive))))
    (libpart (lib conn) (part CONN_02X20)
      (description "Connector, double row, 02x20, pin header")
      (footprints
        (fp Pin_Header_Straight_2X*)
        (fp Pin_Header_Angled_2X*)
        (fp Socket_Strip_Straight_2X*)
        (fp Socket_Strip_Angled_2X*)
        (fp IDC_Header_Straight_*))
      (fields
        (field (name Reference) J)
        (field (name Value) CONN_02X20))
      (pins
        (pin (num 1) (name P1) (type passive))
        (pin (num 2) (name P2) (type passive))
        (pin (num 3) (name P3) (type passive))
        (pin (num 4) (name P4) (type passive))
        (pin (num 5) (name P5) (type passive))
        (pin (num 6) (name P6) (type passive))
        (pin (num 7) (name P7) (type passive))
        (pin (num 8) (name P8) (type passive))
        (pin (num 9) (name P9) (type passive))
        (pin (num 10) (name P10) (type passive))
        (pin (num 11) (name P11) (type passive))
        (pin (num 12) (name P12) (type passive))
        (pin (num 13) (name P13) (type passive))
        (pin (num 14) (name P14) (type passive))
        (pin (num 15) (name P15) (type passive))
        (pin (num 16) (name P16) (type passive))
        (pin (num 17) (name P17) (type passive))
        (pin (num 18) (name P18) (type passive))
        (pin (num 19) (name P19) (type passive))
        (pin (num 20) (name P20) (type passive))
        (pin (num 21) (name P21) (type passive))
        (pin (num 22) (name P22) (type passive))
        (pin (num 23) (name P23) (type passive))
        (pin (num 24) (name P24) (type passive))
        (pin (num 25) (name P25) (type passive))
        (pin (num 26) (name P26) (type passive))
        (pin (num 27) (name P27) (type passive))
        (pin (num 28) (name P28) (type passive))
        (pin (num 29) (name P29) (type passive))
        (pin (num 30) (name P30) (type passive))
        (pin (num 31) (name P31) (type passive))
        (pin (num 32) (name P32) (type passive))
        (pin (num 33) (name P33) (type passive))
        (pin (num 34) (name P34) (type passive))
        (pin (num 35) (name P35) (type passive))
        (pin (num 36) (name P36) (type passive))
        (pin (num 37) (name P37) (type passive))
        (pin (num 38) (name P38) (type passive))
        (pin (num 39) (name P39) (type passive))
        (pin (num 40) (name P40) (type passive)))))
  (libraries
    (library (logical conn)
      (uri /usr/share/kicad/library/conn.lib)))
  (nets
    (net (code 1) (name "Net-(SBC_PIN1-Pad17)")
      (node (ref SBC_PIN1) (pin 17)))
    (net (code 2) (name "Net-(DS1307-Pad1)")
      (node (ref DS1307) (pin 1)))
    (net (code 3) (name "Net-(SBC_PIN1-Pad39)")
      (node (ref SBC_PIN1) (pin 39)))
    (net (code 4) (name "Net-(SBC_PIN1-Pad29)")
      (node (ref SBC_PIN1) (pin 29)))
    (net (code 5) (name "Net-(SBC_PIN1-Pad19)")
      (node (ref SBC_PIN1) (pin 19)))
    (net (code 6) (name "Net-(SBC_PIN1-Pad38)")
      (node (ref SBC_PIN1) (pin 38)))
    (net (code 7) (name "Net-(SBC_PIN1-Pad28)")
      (node (ref SBC_PIN1) (pin 28)))
    (net (code 8) (name "Net-(SBC_PIN1-Pad18)")
      (node (ref SBC_PIN1) (pin 18)))
    (net (code 9) (name "Net-(SBC_PIN1-Pad37)")
      (node (ref SBC_PIN1) (pin 37)))
    (net (code 10) (name "Net-(SBC_PIN1-Pad27)")
      (node (ref SBC_PIN1) (pin 27)))
    (net (code 11) (name GND)
      (node (ref DS1307) (pin 5)))
    (net (code 12) (name "Net-(SBC_PIN1-Pad36)")
      (node (ref SBC_PIN1) (pin 36)))
    (net (code 13) (name "Net-(SBC_PIN1-Pad26)")
      (node (ref SBC_PIN1) (pin 26)))
    (net (code 14) (name "Net-(SBC_PIN1-Pad16)")
      (node (ref SBC_PIN1) (pin 16)))
    (net (code 15) (name "Net-(SBC_PIN1-Pad35)")
      (node (ref SBC_PIN1) (pin 35)))
    (net (code 16) (name "Net-(SBC_PIN1-Pad25)")
      (node (ref SBC_PIN1) (pin 25)))
    (net (code 17) (name "Net-(SBC_PIN1-Pad15)")
      (node (ref SBC_PIN1) (pin 15)))
    (net (code 18) (name "Net-(SBC_PIN1-Pad34)")
      (node (ref SBC_PIN1) (pin 34)))
    (net (code 19) (name "Net-(SBC_PIN1-Pad24)")
      (node (ref SBC_PIN1) (pin 24)))
    (net (code 20) (name "Net-(SBC_PIN1-Pad14)")
      (node (ref SBC_PIN1) (pin 14)))
    (net (code 21) (name "Net-(SBC_PIN1-Pad33)")
      (node (ref SBC_PIN1) (pin 33)))
    (net (code 22) (name "Net-(SBC_PIN1-Pad23)")
      (node (ref SBC_PIN1) (pin 23)))
    (net (code 23) (name "Net-(DS1307-Pad3)")
      (node (ref SBC_PIN1) (pin 3))
      (node (ref DS1307) (pin 3)))
    (net (code 24) (name "Net-(DS1307-Pad4)")
      (node (ref DS1307) (pin 4))
      (node (ref SBC_PIN1) (pin 4)))
    (net (code 26) (name "Net-(SBC_PIN1-Pad13)")
      (node (ref SBC_PIN1) (pin 13)))
    (net (code 27) (name "Net-(DS1307-Pad2)")
      (node (ref SBC_PIN1) (pin 5))
      (node (ref DS1307) (pin 2)))
    (net (code 28) (name "Net-(NANOP1-Pad6)")
      (node (ref NANOP1) (pin 6)))
    (net (code 29) (name "Net-(NANOP1-Pad5)")
      (node (ref NANOP1) (pin 5)))
    (net (code 30) (name "Net-(NANOP1-Pad4)")
      (node (ref NANOP1) (pin 4)))
    (net (code 31) (name "Net-(NANOP1-Pad3)")
      (node (ref NANOP1) (pin 3)))
    (net (code 32) (name "Net-(NANOP1-Pad2)")
      (node (ref NANOP1) (pin 2)))
    (net (code 33) (name "Net-(NANOP1-Pad1)")
      (node (ref NANOP1) (pin 1)))
    (net (code 34) (name "Net-(NANOL1-Pad13)")
      (node (ref NANOL1) (pin 13)))
    (net (code 35) (name "Net-(NANOR1-Pad10)")
      (node (ref NANOR1) (pin 10)))
    (net (code 36) (name "Net-(NANOR1-Pad9)")
      (node (ref NANOR1) (pin 9)))
    (net (code 37) (name "Net-(NANOR1-Pad8)")
      (node (ref NANOR1) (pin 8)))
    (net (code 38) (name "Net-(NANOR1-Pad7)")
      (node (ref NANOR1) (pin 7)))
    (net (code 39) (name "Net-(NANOR1-Pad6)")
      (node (ref NANOR1) (pin 6)))
    (net (code 40) (name "Net-(NANOR1-Pad5)")
      (node (ref NANOR1) (pin 5)))
    (net (code 41) (name "Net-(NANOR1-Pad4)")
      (node (ref NANOR1) (pin 4)))
    (net (code 42) (name "Net-(NANOR1-Pad3)")
      (node (ref NANOR1) (pin 3)))
    (net (code 43) (name "Net-(NANOR1-Pad2)")
      (node (ref NANOR1) (pin 2)))
    (net (code 44) (name "Net-(NANOR1-Pad1)")
      (node (ref NANOR1) (pin 1)))
    (net (code 45) (name "Net-(NANOL1-Pad15)")
      (node (ref NANOL1) (pin 15)))
    (net (code 46) (name "Net-(NANOL1-Pad14)")
      (node (ref NANOL1) (pin 14)))
    (net (code 47) (name "Net-(NANOR1-Pad11)")
      (node (ref NANOR1) (pin 11)))
    (net (code 48) (name "Net-(NANOL1-Pad12)")
      (node (ref NANOL1) (pin 12)))
    (net (code 49) (name "Net-(NANOL1-Pad11)")
      (node (ref NANOL1) (pin 11)))
    (net (code 50) (name "Net-(NANOL1-Pad10)")
      (node (ref NANOL1) (pin 10)))
    (net (code 51) (name "Net-(NANOL1-Pad9)")
      (node (ref NANOL1) (pin 9)))
    (net (code 52) (name "Net-(NANOL1-Pad8)")
      (node (ref NANOL1) (pin 8)))
    (net (code 53) (name "Net-(NANOL1-Pad7)")
      (node (ref NANOL1) (pin 7)))
    (net (code 54) (name "Net-(NANOL1-Pad6)")
      (node (ref NANOL1) (pin 6)))
    (net (code 55) (name "Net-(NANOL1-Pad5)")
      (node (ref NANOL1) (pin 5)))
    (net (code 56) (name "Net-(NANOL1-Pad4)")
      (node (ref NANOL1) (pin 4)))
    (net (code 57) (name "Net-(NANOL1-Pad3)")
      (node (ref NANOL1) (pin 3)))
    (net (code 58) (name "Net-(NANOL1-Pad2)")
      (node (ref NANOL1) (pin 2)))
    (net (code 59) (name "Net-(SBC_PIN1-Pad8)")
      (node (ref SBC_PIN1) (pin 8)))
    (net (code 60) (name "Net-(SBC_PIN1-Pad32)")
      (node (ref SBC_PIN1) (pin 32)))
    (net (code 61) (name "Net-(SBC_PIN1-Pad22)")
      (node (ref SBC_PIN1) (pin 22)))
    (net (code 62) (name "Net-(SBC_PIN1-Pad12)")
      (node (ref SBC_PIN1) (pin 12)))
    (net (code 63) (name "Net-(SBC_PIN1-Pad31)")
      (node (ref SBC_PIN1) (pin 31)))
    (net (code 64) (name "Net-(SBC_PIN1-Pad21)")
      (node (ref SBC_PIN1) (pin 21)))
    (net (code 65) (name "Net-(SBC_PIN1-Pad11)")
      (node (ref SBC_PIN1) (pin 11)))
    (net (code 66) (name "Net-(SBC_PIN1-Pad40)")
      (node (ref SBC_PIN1) (pin 40)))
    (net (code 67) (name "Net-(SBC_PIN1-Pad30)")
      (node (ref SBC_PIN1) (pin 30)))
    (net (code 68) (name "Net-(SBC_PIN1-Pad20)")
      (node (ref SBC_PIN1) (pin 20)))
    (net (code 69) (name "Net-(SBC_PIN1-Pad10)")
      (node (ref SBC_PIN1) (pin 10)))
    (net (code 70) (name "Net-(SBC_PIN1-Pad9)")
      (node (ref SBC_PIN1) (pin 9)))
    (net (code 71) (name "Net-(NANOL1-Pad1)")
      (node (ref NANOL1) (pin 1)))
    (net (code 72) (name "Net-(SBC_PIN1-Pad7)")
      (node (ref SBC_PIN1) (pin 7)))
    (net (code 73) (name "Net-(SBC_PIN1-Pad6)")
      (node (ref SBC_PIN1) (pin 6)))
    (net (code 74) (name "Net-(SBC_PIN1-Pad2)")
      (node (ref SBC_PIN1) (pin 2)))
    (net (code 75) (name "Net-(SBC_PIN1-Pad1)")
      (node (ref SBC_PIN1) (pin 1)))
    (net (code 76) (name "Net-(NANOR1-Pad15)")
      (node (ref NANOR1) (pin 15)))
    (net (code 77) (name "Net-(NANOR1-Pad14)")
      (node (ref NANOR1) (pin 14)))
    (net (code 78) (name "Net-(NANOR1-Pad13)")
      (node (ref NANOR1) (pin 13)))
    (net (code 79) (name "Net-(NANOR1-Pad12)")
      (node (ref NANOR1) (pin 12)))))